services:
  app:
    image: kitoapii
    # build: .
    container_name: "kitoapic"
    env_file: ".env"
    links: 
      - db
    environment:
      - AWS_REGION=${AWS_REGION}
      - WHITE_RIBBON=${WHITE_RIBBON}
      - BLACK_RIBBON=${BLACK_RIBBON}
      - JWT_KEY=${JWT_KEY}
      - JWT_GEN=${JWT_GEN}
      - PROFILE_PIC_BUCKET=${PROFILE_PIC_BUCKET}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.35
    container_name: ${MYSQL_HOST}
    env_file: ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
